config/routes.rb
PropertyManagement01::Application.routes.draw do
  # resources :buildings
  resources :owners do
    resources :buildings, only: [:index, :new, :create, :update, :destroy, :show]
  end

  root to: "owners#index"
end

app/models/building.rb
class Building < ActiveRecord::Base
  validates :street_address, presence: true
  validates :city, presence: true
  validates :state, presence: true, inclusion: { in: %w(
    AL AK AZ AR CA CO CT DE FL GA HI ID IL IN IA KS KY LA 
    ME MD MA MI MN MS MO MT NE NV NH NJ NM NY NC ND OH OK 
    OR PA RI SC SD TN TX UT VT VA WA WV WI WY) }
  validates :postal_code, presence: true, length: { is: 5 }
  validates :owner, presence: true

  belongs_to :owner,
    inverse_of: :buildings
end

app/models/owner.rb
class Owner < ActiveRecord::Base
  validates :first_name, presence: true
  validates :last_name, presence: true
  validates :email, presence: true, 
    format: { with: /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/,
    message: "Invalid email format" }

  has_many :buildings, 
    # dependent: :nullify #this may be a better option as Adam pointed out.  
    # just need the building's owner foreign key OK as null
    dependent: :destroy,
    inverse_of: :owner

  def full_name
    "#{self.first_name} #{self.last_name}"
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/buildings_controller.rb
class BuildingsController < ApplicationController
  def index
    @owner = Owner.find(params[:owner_id])
    @buildings = Building.order(created_at: :desc)
  end

  def new
    @owner = Owner.find(params[:owner_id])
    @building = Building.new
    @states = ['AL','AK','AZ','AR','CA','CO','CT','DE','FL','GA','HI','ID','IL',
      'IN','IA','KS','KY','LA','ME','MD','MA','MI','MN','MS','MO','MT','NE',
      'NV','NH','NJ','NM','NY','NC','ND','OH','OK','OR','PA','RI','SC','SD',
      'TN','TX','UT','VT','VA','WA','WV','WI','WY']
  end

  def create
    @building = Building.new(building_params)
    @owner = Owner.find(params[:owner_id])
    @building.owner_id = @owner.id
    # @building.owner_id = params[:owner_id] ## isn't enough
    if @building.save
      redirect_to new_owner_building_path(@owner), 
        notice: 'Building added!'
    else
      render 'buildings/new'
    end
  end

  private

  def building_params
    params.require(:building)
      .permit(:street_address, :city, :state, :postal_code, :description)
  end
end

app/controllers/owners_controller.rb
class OwnersController < ApplicationController
  def index
    @owners = Owner.order(updated_at: :desc)
  end

  def show
    @owner = Owner.find(params[:id])
    # @buildings = Building.where(owner_id: @owner.id)
    # refresh your SQL and ARel to get the buildings of this owner.
  end

  def new
    @owner = Owner.new
  end

  def create
    @owner = Owner.new(owner_params)
    if @owner.save
      redirect_to new_owner_path,
        notice: 'Owner added!'
      else
        render :new
      end
  end

  private

  def owner_params
    params.require(:owner)
      .permit(:first_name, :last_name, :email, :company_name)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/buildings/index.html.erb
<h3>All the Buildings</h3>

<table>
  <tr>
    <th>Address</th>
  </tr>
  <% @buildings.each do |building| %>
    <tr>
      <td><%= building.street_address %></td>
    </tr>
  <% end %>
</table>

<p><%= link_to 'Add a Building', new_building_path %></p>

app/views/buildings/new.html.erb
<h4>Add Building</h4>

<%= simple_form_for [@owner, @building] do |f| %>
  <div class="row">
    <div class="small-12 columns">
      <%= f.input :street_address, label: 'Street Address' %>
    </div>
  </div>
  <div class="row">
    <div class="small-12 medium-4 columns">
      <%= f.input :city %>
    </div>
    <div class="small-12 medium-4 columns">
      <%= f.input :state, collection: @states %>
    </div>
    <div class="small-12 medium-4 columns">
      <%= f.input :postal_code, label: 'Postal Code' %>
    </div>
  </div>
  <div class="row">
    <div class="small-12 columns">
        <%= f.input :description, as: :text %>
    </div>
  </div>
  <div> <!-- couldn't get button size or shape to change -->
    <%= f.button :submit, 'Add Building' %>
  </div>
<% end %>

<p><%= link_to "Back to Owner", owner_path(@owner) %></p>

app/views/buildings/show.html.erb
<h3><%= @building.street_address %></h3>

<table>
  <tr>
    <th>City</th>
    <th>State</th>
    <th>Postal Code</th>
  </tr>
  <tr>
    <%= @building.city %>
    <%= @building.state %>
    <%= @building.postal_code %>
  </tr>
</table>

<p><%= link_to 'Building Home', owner_buildings_path %></p>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />

    <title><%= content_for?(:title) ? yield(:title) : "foundation-rails" %></title>

    <%= stylesheet_link_tag    "application" %>
    <%= javascript_include_tag "vendor/modernizr" %>
    <%= csrf_meta_tags %>
  </head>

  <body>
    <div class="row">
      <div class="small-12 columns">
        <%= yield %>
        <%= javascript_include_tag "application" %>
      </div>
    </div>
  </body>
</html>

app/views/owners/index.html.erb
<h3>All the Owners</h3>

<table>
  <tr>
    <th>Name</th>
  </tr>
  <% @owners.each do |owner| %>
    <tr>
      <td><%= owner.full_name %></td>
    </tr>
  <% end %>
</table>

<p><%= link_to 'Add an Owner', new_owner_path %></p>

app/views/owners/new.html.erb
<h3>Add Owner</h3>

<%= simple_form_for @owner do |f| %>
  <%= f.input :first_name, label: 'First Name', input_html: { size: 30 } %>
  <%= f.input :last_name, label: 'Last Name', input_html: { size: 30 } %>
  <%= f.input :email, input_html: { size: 30 } %>
  <%= f.input :company_name, label: 'Company Name', input_html: { size: 30 } %>
  <%= f.button :submit, 'Add Owner' %>
<% end %>

app/views/owners/show.html.erb
<h3><%= @owner.full_name %></h3>

<div class="row">
  <table>
    <tr>
      <th>Email</th>
      <th>Company Name</th>
      <th>Building Addresses</th>
    </tr>
    <tr>
      <td><%= @owner.email %></td>
      <td><%= @owner.company_name %></td>
      <td>
        <% @owner.buildings.each do |building| %>
          <li><%= building.street_address %></li>
        <% end %>
      </td>
    </tr>
  </table>
</div>

<p><%= link_to 'Add a Building', new_owner_building_path(@owner) %></p>
<p><%= link_to "All #{@owner.first_name}'s Buildings", 
  owner_buildings_path(@owner) %></p>